### ISSUE TITLE
 New dependency name: uglify-es => terser #1 

### ISSUE THREAD

**Issue by fabiosantoscode** [zhang2333/uglify-es-loader#1]
There has been development on a new fork of uglify-es, which is now called terser and has its own package!

    "terser": "^3.7.3"

Please upgrade to our new version.

**Comment by iamsisar** [comment]
any chances to see updates on this?

**Comment by fabiosantoscode** [comment]
Development has continued and now the fork has a lot of adoption

**Comment by zhang2333** [comment]
@fabiosantoscode Thanks for your reminder.
